# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-20 14:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='image',
            field=models.CharField(default='https://www.mediafire.com/convkey/82cc/5pherhmaeju7un56g.jpg?size_id=5', max_length=1000),
        ),
    ]
