# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-20 13:50
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0003_blog'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blog',
            name='admin_user',
        ),
        migrations.RemoveField(
            model_name='user',
            name='blog_name',
        ),
        migrations.DeleteModel(
            name='Blog',
        ),
    ]
