# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-20 14:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0005_auto_20170420_1705'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='user_image',
            field=models.CharField(default='https://www.mediafire.com/convkey/9870/99zv8tz2ai0jndl6g.jpg?size_id=5', max_length=1000),
        ),
    ]
